name: CI

on:
  push:
  workflow_dispatch:
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: ts-graphviz/setup-graphviz@v2
