name: CI

on: [push]
jobs:
  test1:
    name: Test 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: ts-graphviz/setup-graphviz@v1.1.0-1
        with:
          ubuntu-graphviz-version: '2.42.2-3build2'
          ubuntu-libgraphvizdev-version: '2.42.2-3build2'
          windows-graphviz-version: '2.49.3'

  test2:
    name: Test 2
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: ts-graphviz/setup-graphviz@v1.1.0-1
