name: CI

on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: ts-graphviz/setup-graphviz@v1.1.0-0
        with:
          ubuntu-graphviz-version: '2.42.2-3build2'
          ubuntu-libgraphvizdev-version: '2.42.2-3build2'
          macos-graphviz-version: '3.0.0'
          windows-graphviz-version: '2.49.3'
