name: CI

on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-18.04
    steps:
      - uses: ts-graphviz/setup-graphviz@v1.0.1-0
